// top layer file
// header component?

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VidAgent",
  description: "Generated by create next app",
  icons: {
    icon: "ref",
  },
  // openGraph: {
  //   type: "website",
  //   locale: "en_US",
  //   url: "https://vidagent.com",
  //   siteName: "VidAgent",
  //   images: [
  //     {
  //       url: "https://vidagent.com/og.png",
  //       width: 800,
  //       height: 600,
  //       alt: "VidAgent",
  //     },
  //   ],
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientWrapper>
          <Header />
          <main> {children} </main>
        </ClientWrapper>

      </body>
    </html>
  );
}
